spring:
  main:
    banner-mode: off
  application:
    name: spring-lib-prcte
  docker:
    compose:
      enabled: false
  ai:
    model:
      embedding:
        text: google-genai
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: spring-collection
        use-tls: false
        initialize-schema: true
    google:
      genai:
        embedding:
          api-key: ${GEMINI_API_KEY}
          project-id: ${GOOGLE_CLOUD_PROJECT}
          location: ${GOOGLE_CLOUD_LOCATION}
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768